production: &production
  name: Locale
  s3_bucket: townhall-country-state-majorlocale-locale
  s3_access_key: key
  s3_secret_key: secret
  base_url: http://locale.majorlocale.state.townhall.us
  facebook_app_id: 1
  facebook_app_secret: abc
  system_user_token: thisshouldbeunique

development:
  <<: *production
  base_url: http://localhost:3000

test:
  name: Locale
  s3_bucket: townhall-country-state-majorlocale-locale
  s3_access_key: key
  s3_secret_key: secret
  base_url: http://locale.majorlocale.state.townhall.us
  facebook_app_id: 1
  facebook_app_secret: abc
  system_user_token: thisshouldbeunique
